-- AgOptics Well Registration — Supabase schema
-- Run this in the Supabase dashboard: SQL Editor → New query → paste → Run.
-- Safe to re-run any time: every statement is idempotent (IF NOT EXISTS),
-- so re-running after an update only adds what's new.
--
-- Two groups of tables:
--
-- 1. Submission archive (original): one row in `registrations` per grower
--    "Email summary to AgOptics" submission, with the wells in `wells`.
--
-- 2. Grower portal (pilot study): growers sign in with an emailed code and
--    their parcels/wells persist across visits so they can return to add
--    more wells or make changes.
--      growers        — one row per grower account (keyed by email)
--      login_codes    — short-lived 6-digit sign-in codes (hashed)
--      grower_parcels — the grower's saved parcel list (from their import)
--      grower_wells   — the grower's saved wells (the live, editable set)
--
-- Row Level Security is enabled with NO policies: the anon/public keys can't
-- read or write anything. Only the site's serverless functions (using the
-- service role key stored in Netlify/Vercel env vars) can touch the data,
-- and only you can browse it in the Supabase dashboard.

create table if not exists registrations (
  id uuid primary key default gen_random_uuid(),
  landowner text not null,
  contact text,
  email text,
  gsa text,
  summary text,
  created_at timestamptz not null default now()
);

create table if not exists wells (
  id uuid primary key default gen_random_uuid(),
  registration_id uuid not null references registrations(id) on delete cascade,
  label text,
  well_use text,
  status text,
  apn text,
  gsa text,
  depth_ft numeric,
  well_no text,
  latitude double precision,
  longitude double precision,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists wells_registration_idx on wells (registration_id);
create index if not exists wells_gsa_idx on wells (gsa);

alter table registrations enable row level security;
alter table wells enable row level security;

-- ---------------------------------------------------------------------------
-- Grower portal tables
-- ---------------------------------------------------------------------------

create table if not exists growers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  name text,
  contact text,
  gsa text,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists login_codes (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts int not null default 0,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists login_codes_email_idx on login_codes (email, created_at desc);

create table if not exists grower_parcels (
  id uuid primary key default gen_random_uuid(),
  grower_id uuid not null references growers(id) on delete cascade,
  apn text not null,
  gsa text,
  label text,
  acres numeric,
  sort_order int,
  created_at timestamptz not null default now(),
  unique (grower_id, apn)
);

create index if not exists grower_parcels_grower_idx on grower_parcels (grower_id);

-- The grower's live well set. `id` is generated by the app (crypto.randomUUID)
-- so edits made offline can be reconciled by upsert when the device reconnects.
create table if not exists grower_wells (
  id uuid primary key,
  grower_id uuid not null references growers(id) on delete cascade,
  label text,
  well_use text,
  status text,
  apn text,
  gsa text,
  depth_ft numeric,
  well_no text,
  latitude double precision,
  longitude double precision,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists grower_wells_grower_idx on grower_wells (grower_id);

-- Link "Email summary to AgOptics" submissions to the signed-in account.
alter table registrations add column if not exists grower_id uuid references growers(id);

alter table growers enable row level security;
alter table login_codes enable row level security;
alter table grower_parcels enable row level security;
alter table grower_wells enable row level security;
